{% set name = "spacy" %}
{% set version = "1.7.3" %}
{% set sha256sum = "ff82b94f22455ed6d328b914a6340591fda442a3f8ee84bdbe23c7b845cc0e23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Remove-HE-package-references-from-tests.patch

build:
  number: 0
  script: python setup.py install -q --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain   # [unix]
    - msinttypes  # [win and py27]
    - python
    - setuptools
    - numpy x.x
    - numpy >=1.7

  run:
    - python
    - numpy x.x
    - numpy >=1.7
    - murmurhash >=0.26,<0.27
    - cymem >=1.30,<1.32.0
    - preshed >=1.0.0,<2.0.0
    - thinc >=6.5.0,<6.6.0
    - plac >=0.9.6,<1.0.0
    - six
    - pathlib  # [py2k]
    - ujson >=1.35
    - dill >=0.2,<0.3
    - requests >=2.13.0,<3.0.0
    - pip

test:
  requires:
    - pytest

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io/docs
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rolando
    - ines
