{% set name = "spacy" %}
{% set version = "2.0.2" %}
{% set sha256sum = "875eb7bf713093840caa27f8f0f1968dcc701f9b2c775b5bfde36ed3a76369c2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install -q --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain   # [unix]
    - msinttypes  # [win and py27]
    - python
    - setuptools
    # Pin numpy at build time with the minimum version available.
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - gcc        # [linux]
  run:
    - python
    - libgcc     # [linux]
    - numpy >=1.7
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]
    - murmurhash >=0.28,<0.30
    - cymem >=1.30,<1.32.0
    - preshed >=1.0.0,<2.0.0
    - thinc >=6.10.0,<6.11.0
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - pathlib  # [py2k]
    - ujson >=1.35
    - dill >=0.2,<0.3
    - requests >=2.11.0,<3.0.0
    - regex >=2017.4.1,<2017.12.1
    - ftfy >=4.4.2,<5.0.0
    - pip
    - msgpack-numpy >=0.4.1,<0.5.0
    - msgpack-python >=0.4.8,<0.5.0

test:
  requires:
    - pytest
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io/docs
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
