{% set name = "spacy" %}
{% set version = "1.6.0" %}
{% set sha256sum = "18df95985cebf017250d14bb2a6d5a97c3f5e58d54f7e2ac319246fd3d00d841" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

# Numpy version supported is >= 1.7.
requirements:
  build:
    - toolchain   # [unix]
    - msinttypes  # [win and py27]
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x
    - murmurhash >=0.26,<0.27
    - cymem >=1.30,<1.32.0
    - preshed >=0.46.1,<0.47
    - thinc >=6.2.0,<6.3.0
    - plac
    - six
    - cloudpickle
    - pathlib  # [py2k]
    - sputnik >=0.9.2,<0.10.0
    - ujson >=1.35

test:
  requires:
    - pytest

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io/docs
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rolando
