appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: tMK4Q3PYEp/nSe7NxGtfrj4KaB0TydPbNTllqSEVpG6qv6JRhfqFCFQSvn0xMQ0sHX7X8Sr9vW5yHpyPIAeVrD3hNUfy2kAXJDJkQ0p0aVuMISZ2YItvOFl8ynCKbEQSR8+c6C4fBiNS3XkuMeO0gzaeEmzcWCLdj1r+FY8UqJ1SYJNZgTWcOCki923bEBk39gWv4PR30/vBYToVWz4vU8E/8kMuGHvrW//jb4R52kgi0LJt8ZgLoxXVIFNIpPjNn6P23Qc7WvUcVcu9IoQwM8PhQmk8x5urErKasWjQSzH9Ga20RuKz3q3L34FpZH/qKQZxhlGF+Wfw8SiKn4Zk5NkZ/fBchhQQKF698xWLPJ4Fhfvu05Gbwq3+JT+JXr3fEiX2nyD3oWDWPLtNI+vhXD35wQj1NSvdPXguvlfo+nrcANFi/xmd1bB8Dfu6rwZcOKQpnVgY6UyyLm4SgakL4jSFooCVFFT4J3FqxeBPYMYoFSOg3PYQFEVs73THt8zF05AoDNYrLUWnyhfuiSf7N/aB4N1lLt0V3Hr1L9SkX2JMYE/KTB7HSPIiR42FW85bfyl8D4H7eQa2zbKHIDLgx2dcQ/jc4Ywe0fbg+do38ty5PL4qOUW6G4csa5EKq9QqKRO5f915uOofbxyA6gPzcVrN7unMeaqugT8ChgmtnRs=}
provider:
  win: azure
conda_forge_output_validation: true
